### ISSUE TITLE
How does this compare to JScrambler?

### ISSUE THREAD

**Issue by AhsanE** [javascript-obfuscator/javascript-obfuscator-ui#12]

**Comment by sanex3339** [comment]
It free.

**Comment by AhsanE** [comment]
There is a small issue, some API names remain non-obfuscated. Please try the JScrambler at max settings, and then this. This is better except for one tiny thing, that is that API names are not all obfuscated.

**Comment by sanex3339** [comment]
What names? All global variables without declaration wont be obfuscated. For example `Date`, `Map`, and others.

**Comment by AhsanE** [comment]
math.random and math.pi, for example, are not obfuscated

**Comment by sanex3339** [comment]
Yes, because this are global variables without declaration. They cannot be obfuscated right now.

It can be transformed to the following format: `window['Math'].random()` but this approach will bring many problems.

Obfuscator transforming variables by finding variable declaration first. If variable haven't declaration - it won't be obfuscated. So, all global variables are under this rule.

If i want to detect global system variables - i should use predefined list.
But obfuscator should be environments - independent. 

So in what format i should transform this code?

```
console.log(Math.random());
```

For browser - `window['Math'].random`.
For `node.js` - `global['Math'].random`.

Two absolutely different global objects and each of then wont work under other environments.
If you have some good ideas - welcome.

**Comment by AhsanE** [comment]
We have to make a trade-off here. Make 2 options, one for server code, the other for browser code. This is what Jscrambler does, they give us an option to select a web app or browser app, or if it is a server code.

**Comment by sanex3339** [comment]
This is correct about two output options (`client` and `server`) in `jscrambler`?
If yes - i can add same options and this also partially solve problem with `eval`.

**Comment by AhsanE** [comment]
Yes, this seems to be the solution to this for now.

**Comment by sanex3339** [comment]
Can you make issue for this option in the main repository?
