### ISSUE TITLE
the Obfuscate button doesn't work

### ISSUE THREAD

**Issue by demidovakatya** [javascript-obfuscator/javascript-obfuscator-ui#4]
This button doesn't work :(
![i 2016-12-17 at 18 24 36](https://cloud.githubusercontent.com/assets/5788652/21287869/18375398-c486-11e6-80e5-4af59056a40e.png)

Browser/os:
- Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/602.2.14 (KHTML, like Gecko) Version/10.0.1 Safari/602.2.14
- Operating system OS X 10.12.1
- Javascript enabled Yes
- Cookies enabled Yes
- Flash version Not installed
- Java version Not installed
- Websockets supported Yes

**Comment by slig** [comment]
Hi!

Thanks for filling this issue. I tested on Safari and I'm able to reproduce this error.

Looks like Safari doesn't have [this feature](http://caniuse.com/#search=fetch). It's possible to fix, but in the meantime can you please use the site on Chrome or Firefox?

Since most devs use Chrome/Firefox and this tool is used exclusively by developers, I usually don't bother testing on IE and Safari.

**Comment by demidovakatya** [comment]
well... do you have google analytics or smth else to be aware of your audience? :)

**Comment by slig** [comment]
Yes I do, good idea! Here's the browser stats for the last 30 days.

<img width="675" alt="screen shot 2016-12-17 at 17 25 27" src="https://cloud.githubusercontent.com/assets/37779/21289192/f3ee85cc-c47d-11e6-8c47-a715cb22f600.png">
