### ISSUE TITLE
Add eval for obfuscated code

### ISSUE THREAD

**Issue by sanex3339** [javascript-obfuscator/javascript-obfuscator-ui#6]
Hi, it's hard to add console-like execution for obfuscated code like here?
https://babeljs.io/repl/

It will help peoples to see that their code works after obfuscation.

**Comment by slig** [comment]
Sorry, I did not get the email notification from this issue, I'm only seeing it now.

I don't think it's hard, but I wonder how it's useful since, I believe, most of the code that is obfuscated depends on external events and actions in order to work. So evaluating them will render nothing.

This is pure guessing on my part. What do you think?

**Comment by sanex3339** [comment]
>  So evaluating them will render nothing.

Yep, but for simple code it's nice and will show that obfuscator working properly.

**Comment by slig** [comment]
I see. I will implement it then.

**Comment by sanex3339** [comment]
Thank you!

**Comment by sanex3339** [comment]
HI. Any ETA?

**Comment by slig** [comment]
Hi, sorry! I did not forget about it. Things are rough at $dayjob and I couldn't do it yet. I'm hoping to do it at most along with the changes for the 0.10 release.

**Comment by slig** [comment]
Deployed this feature right now.

It's not perfect. Due the way that the `console.log` calls are logged in order to be shown in the interface, it may look like the option `disableConsoleOutput` isn't working as because everything is logged regardless of this option.

Also, I had to remove the `pretty-format` package because has modern JS features that uglify doesn't support yet. (only discovered this issue as I making the deploy, locally it worked fine).

If you have any suggestion, just let me know!

**Comment by sanex3339** [comment]
I think, that you just can disable `evaluate` checkbox if `disableConsoleOutput` is enabled.
Maybe with some text that will describe why this checkbox is disabled.

**Comment by slig** [comment]
Nice suggestion. Will try to implement it soon.
